#ifndef STM32_F1XX_H
#define STM32_F1XX_H

#include <stdint.h>

#define __vo volatile /* Define a volatile type for memory-mapped registers */
#define __io volatile

#define FLASH_BASE_ADDRESS 0x80000000U /* Base address of the Flash memory */
#define SRAM_BASE_ADDRESS 0x20000000U  /* Base address of the SRAM memory*/

#define PERIPH_BASE_ADDRESS 0x40000000U							 /* Base address of the peripheral registers */
#define APB1PERIPH_BASE_ADDRESS (PERIPH_BASE_ADDRESS + 0x00U)	 /* Base address of APB2 peripherals (0x00 gap address)*/
#define APB2PERIPH_BASE_ADDRESS (PERIPH_BASE_ADDRESS + 0x10000U) /* Base address of APB1 peripherals */
#define AHBPERIPH_BASE_ADDRESS (PERIPH_BASE_ADDRESS + 0x18000U)	 /* Base address of AHB peripherals */

/* APB1 peripherals */
#define TIM2_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x0000U)  /* TIM2 */
#define TIM3_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x0400U)  /* TIM3 */
#define TIM4_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x0800U)  /* TIM4 */
#define TIM5_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x0C00U)  /* TIM5 */
#define TIM6_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x1000U)  /* TIM6 */
#define TIM7_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x1400U)  /* TIM7 */
#define TIM12_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x1800U) /* TIM12 */
#define TIM13_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x1C00U) /* TIM13 */
#define TIM14_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x2000U) /* TIM14 */

#define RTC_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x2800U)  /* RTC */
#define WWDG_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x2C00U) /* Window Watchdog */
#define IWDG_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x3000U) /* Independent Watchdog */

#define SPI2_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x3800U) /* SPI2/I2S */
#define SPI3_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x3C00U) /* SPI3/I2S */

#define USART2_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x4400U) /* USART2 */
#define USART3_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x4800U) /* USART3 */
#define UART4_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x4C00U)	/* UART4 */
#define UART5_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x5000U)	/* UART5 */

#define I2C1_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x5400U) /* I2C1 */
#define I2C2_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x5800U) /* I2C2 */

#define USB_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x5C00U)	  /* USB FS */
#define USB_SRAM_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x6000U) /* Shared USB/CAN SRAM */

#define CAN1_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x6400U) /* CAN1 */
#define CAN2_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x6800U) /* CAN2 */

#define BKP_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x6C00U) /* Backup Registers */
#define PWR_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x7000U) /* Power Control */
#define DAC_BASE_ADDRESS (APB1PERIPH_BASE_ADDRESS + 0x7400U) /* DAC */

/* APB2 peripherals */
#define AFIO_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x0000U) /* AFIO */
#define EXTI_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x0400U) /* EXTI */

#define GPIOA_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x0800U) /* GPIOA */
#define GPIOB_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x0C00U) /* GPIOB */
#define GPIOC_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x1000U) /* GPIOC */
#define GPIOD_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x1400U) /* GPIOD */
#define GPIOE_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x1800U) /* GPIOE */
#define GPIOF_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x1C00U) /* GPIOF */
#define GPIOG_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x2000U) /* GPIOG */

#define ADC1_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x2400U) /* ADC1 */
#define ADC2_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x2800U) /* ADC2 */

#define TIM1_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x2C00U)	/* TIM1 */
#define SPI1_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x3000U)	/* SPI1 */
#define TIM8_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x3400U)	/* TIM8 */
#define USART1_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x3800U) /* USART1 */
#define ADC3_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x3C00U)	/* ADC3 */

#define TIM9_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x4C00U)  /* TIM9 */
#define TIM10_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x5000U) /* TIM10 */

#define TIM11_BASE_ADDRESS (APB2PERIPH_BASE_ADDRESS + 0x5400U) /* TIM11 */

/* APHB peripherals */
#define SDIO_BASE_ADDRESS (PERIPH_BASE_ADDRESS + 0x0000U)				/* SDIO */
#define DMA1_BASE_ADDRESS (AHBPERIPH_BASE_ADDRESS + 0x2000U)			/* DMA1 */
#define DMA2_BASE_ADDRESS (AHBPERIPH_BASE_ADDRESS + 0x400U)				/* DMA2 */
#define RCC_BASE_ADDRESS (AHBPERIPH_BASE_ADDRESS + 0x1000U)				/* RCC */
#define FLASH_INTERFACE_BASE_ADDRESS (AHBPERIPH_BASE_ADDRESS + 0x2000U) /* Flash interface */
#define CRC_BASE_ADDRESS (AHBPERIPH_BASE_ADDRESS + 0x3000U)				/* CRC calculation unit */
#define ETH_BASE_ADDRESS (AHBPERIPH_BASE_ADDRESS + 0x8000U)				/* Ethernet MAC */
#define USB_OTG_FS_BASE_ADDRESS (AHBPERIPH_BASE_ADDRESS + 0xFFE8000U)	/* USB OTG FS */
#define FSMC_BASE_ADDRESS (AHBPERIPH_BASE_ADDRESS + 0x50000000U)		/* FSMC */

typedef struct
{
	__vo uint32_t CR;
	__vo uint32_t CFGR;
	__vo uint32_t CIR;
	__vo uint32_t APB2RSTR;
	__vo uint32_t APB1RSTR;
	__vo uint32_t AHBENR;
	__vo uint32_t APB2ENR;
	__vo uint32_t APB1ENR;
	__vo uint32_t RCC_BDCR;
} RCC_TypeDef;

// typedef struct
// {
// 	__vo uint32_t MODER;
// 	__vo uint32_t OTYPER;
// 	__vo uint32_t OSPEEDR;
// 	__vo uint32_t PUPDR;
// 	__vo uint32_t IDR;
// 	__vo uint32_t ODR;
// 	__vo uint32_t BSSR;
// 	__vo uint32_t LCKR;
// 	__vo uint32_t AFR[2];
// 	__vo uint32_t BRR;

// } GPIO_RefDef_t;

// #define GPIOA ((RCC_TypeDef *)GPIOA_BASE_ADDRESS) /*GPIOA*/
// #define GPIOB ((RCC_TypeDef *)GPIOB_BASE_ADDRESS) /*GPIOB*/
// #define GPIOC ((RCC_TypeDef *)GPIOC_BASE_ADDRESS) /*GPIOC*/
// #define GPIOD ((RCC_TypeDef *)GPIOD_BASE_ADDRESS) /*GPIOD*/
// #define GPIOE ((RCC_TypeDef *)GPIOE_BASE_ADDRESS) /*GPIOE*/
// #define GPIOF ((RCC_TypeDef *)GPIOF_BASE_ADDRESS) /*GPIOF*/
// #define GPIOG ((RCC_TypeDef *)GPIOG_BASE_ADDRESS) /*GPIOG*/

#define RCC ((RCC_TypeDef *)0x40021000) 


#define RCC_APB2ENR_GPIOAEN (1U << 2)
#define RCC_APB2ENR_GPIOBEN (1U << 3)
#define RCC_APB2ENR_GPIOCEN (1U << 4)
#define RCC_APB2ENR_GPIODEN (1U << 5)
#define RCC_APB2ENR_GPIOEEN (1U << 6)
#define RCC_APB2ENR_GPIOFEN (1U << 7)
#define RCC_APB2ENR_GPIOGEN (1U << 8)



#define GPIOA_PCLOCK_EN() (RCC->APB2ENR |= RCC_APB2ENR_GPIOAEN)
#define GPIOB_PCLOCK_EN() (RCC->APB2ENR |= RCC_APB2ENR_GPIOBEN)
#define GPIOC_PCLOCK_EN() (RCC->APB2ENR |= RCC_APB2ENR_GPIOCEN)
#define GPIOD_PCLOCK_EN() (RCC->APB2ENR |= RCC_APB2ENR_GPIODEN)
#define GPIOE_PCLOCK_EN() (RCC->APB2ENR |= RCC_APB2ENR_GPIOEEN)
#define GPIOF_PCLOCK_EN() (RCC->APB2ENR |= RCC_APB2ENR_GPIOFEN)
#define GPIOG_PCLOCK_EN() (RCC->APB2ENR |= RCC_APB2ENR_GPIOGEN)



#endif